# Bloco de informações da aplicação
app:
  description: Módulo administrativo

server:
  port: ${MODULO_SERVICE_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME} # Adicionar um valor padrão é uma boa prática
  
  # Configuração do Banco de Dados
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Tempo máximo que uma conexão pode viver no pool (ex: 10 minutos = 600000 ms).
      # Use um valor um pouco menor que o timeout do seu firewall ou banco de dados.
      max-lifetime: 600000
      # Tempo que uma conexão pode ficar ociosa antes de ser removida do pool (ex: 5 minutos).
      idle-timeout: 300000
      # (Recomendado) Frequência com que o Hikari fará um "ping" em conexões ociosas
      # para evitar que sejam fechadas pela rede (ex: a cada 2 minutos).
      keepalive-time: 120000
      # Tempo máximo que a aplicação vai esperar por uma conexão do pool.
      connection-timeout: 30000
  
  # Configuração do JPA e Hibernate
  jpa:
    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate} # 'validate' é mais seguro que 'update' em produção
      ddl-auto: validate # 'validate', 'create', 'update' é mais seguro que 'update' em produção
#    show-sql: ${SPRING_JPA_SHOW_SQL:false} # Simplificado para o padrão do Spring Boot
    show-sql: true # Simplificado para o padrão do Spring Boot
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
        # A plataforma do banco de dados geralmente é detectada automaticamente
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Configuração do GraphQL
  graphql:
    path: /graphql # Caminho principal da API GraphQL (simplificado)
    graphiql:
      enabled: true # Habilita a interface, que estará em /graphiql (caminho padrão)
    # CUIDADO: As configurações de erro abaixo são ótimas para DEV, mas inseguras para PROD.
    # Em produção, considere desabilitar a inclusão de exceções e stack traces.
    errors:
      include-exception: true # Mude para false em produção
      include-message: always
      include-stacktrace: always # Mude para never em produção
      include-binding-errors: always
    # CUIDADO: Permitir todas as origens é inseguro para produção.
    cors:
      allowed-origins: "*" # Em produção, especifique os domínios permitidos.
      allowed-methods: "GET, POST"

  jackson:
    default-property-inclusion: ALWAYS

#    ALWAYS: Garante que todas as propriedades sejam incluídas no JSON, independentemente do seu valor (incluindo null). Esta é a configuração que o Apollo Client espera para campos anuláveis.
#    NON_NULL: (O que você usou) Exclui propriedades que têm valor null.
#    NON_EMPTY: Exclui propriedades que são null ou vazias (strings vazias, coleções vazias, etc.).
#    NON_ABSENT: Exclui propriedades que são null ou Optional.empty().

  # Spring DevTools para hot-reloading em desenvolvimento
#  devtools:
#    restart:
#      poll-interval: 2s
#      quiet-period: 1s

# Configuração do cliente Eureka para Service Discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_MODULO_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true

# Configurações de segurança específicas da aplicação
application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: 86400000 # 24 horas

# Endpoints do Actuator expostos
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Exponha apenas o necessário (health e info são comuns)

# Níveis de Log
logging:
  level:
    # Nível raiz para logs da aplicação
    com.escola.admin: INFO # Ajuste para o seu pacote base
    org.springframework.security: INFO
    org.hibernate.SQL: INFO # Útil para ver as queries SQL geradas
    org.hibernate.type.descriptor.sql: TRACE # Útil para ver os parâmetros das queries
    # Isso mostrará detalhes da construção da requisição e da resposta do WebClient
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    # Isso pode ajudar a ver detalhes da codificação/decodificação do GraphQL
#    org.springframework.graphql.client: INFO
#    org.springframework.data.jpa: DEBUG
#    org.hibernate.type: TRACE
#    org.hibernate.engine.spi.CollectionLoadContext: TRACE